runs:
  using: composite
  steps:
    - name: Setup Node v16
      uses: actions/setup-node@v2
      with:
        node-version: "20.3.0"
    - name: Install Yarn
      shell: bash
      run: npm install -g yarn
    - name: Install Dependencies
      shell: bash
      run: yarn install --production
