name: Deploy to Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  check-for-tests-sucsess:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Tests passed, beginning deployment"

  create-tag:
    runs-on: ubuntu-latest
    needs: check-for-tests-sucsess
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        id: get_version
        run: echo version="v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get_version.outputs.version }}

  build:
    runs-on: ubuntu-latest
    needs: check-for-tests-sucsess
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialise Project
        uses: ./.github/actions/initialise-project
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
