name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialise Project
        uses: ./.github/actions/initialise-project
      - name: Build Project
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialise Project
        uses: ./.github/actions/initialise-project
      - name: Lint Project
        run: yarn lint
